--- 
apiVersion: v1 
kind: Namespace
metadata:
  name: db-ns 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: db-ns 
  labels:
    app: db 
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: db-ns
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      name: db-po
  template:
    metadata:
      name: db-po
      labels:
        app: db
        name: db-po
    spec: 
      volumes: 
        - name: data-vol
          persistentVolumeClaim:
            claimName: db-pvc
      containers:
      - name: db-container
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: data-vol

