---
apiVersion: v1
kind: ConfigMap
data:
  index-html: /
  about-html: about

---
apiVersion: v1 
kind: Pod 
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  volumes:
    - name: html-vol
      configMap:
        name: htmls 
    - name: tmp-vol 
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx:1.25
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-vol 
          readOnly: true
        - mountPath: /opt/tmp
          name: tmp-vol