---
version: "3.8"

services:
  myapp:
    image: stackupiss/northwind-app:v1
    container_name: myapp
    environment:
    - DB_HOST=mydb
    - DB_USER=root
    - DB_PASSWORD=changeit
    ports:
     - "8080:3000"
    links: 
    - "mydb:db"
    networks:
    - mynet

  mydb:
    image: stackupiss/northwind-db:v1
    container_name: mydb
    volumes:
     - myvol:/var/lib/mysql
    networks:
    - mynet

networks:
  mynet:
    name: mynet

volumes:
  myvol:
    name: myvol