---
apiVersion: v1
kind: Namespace
metadata:
  name: bggns
  labels:
    app: bgg

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy 
  namespace: bggns 
  labels:
    app: bgg

spec:
  selector:
    matchLabels:
      name: bggdb-po 
      app: bgg
  template:
    metadata:
      name: bggdb-po
      labels:
        name: bggdb-po
        app: bgg
    spec:
      containers:
      - name: bggdb
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy 
  namespace: bggns 
  labels:
    app: bgg

spec:
  selector:
    matchLabels:
      name: bggapp-po 
      app: bgg
  template:
    metadata:
      name: bggapp-po
      labels:
        name: bggapp-po
        app: bgg
    spec:
      containers:
      - name: bggapp
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
          - name: BGG_DB_USER
            value: root
          - name: BGG_DB_HOST
            value: mydb-svc
          - name: BGG_DB_PASSWORD
            value: changeit
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
  replicas: 3

---
apiVersion: v1
kind: Service
metadata:
  name: mydb-svc
  namespace: bggns
  labels:
    app: bgg
spec:
  type: ClusterIP
  selector:
    name: bggdb-po
    app: bgg
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: dov-bear
spec:
  type: LoadBalancer  
  selector:
    name: bggapp-po
    app: bgg
  ports:
  - port: 8080
    targetPort: 3000